#griffin_filter_sites.snakefile
#Anna-Lisa Doebley
#Template made 2021-05-16
#Ha Lab
#Fred Hutchinson Cancer Research Center

#SELECT CORRECT REFERENCE GENOME
#reference genome for alignment, with index files in same folder as .fa file
reference_genome:
    /fh/fast/ha_g/grp/reference/GRCh38/GRCh38.fa

#SELECT CORRECT MAPABILITY DATA
#must match genome
mapability_track:
    /fh/fast/ha_g/user/adoebley/projects/griffin_paper/downloads/genome/k50.Umap.MultiTrackMappability.hg38.bw

#select where the bed files will go after splitting by mapability
split_by_mapability_dir:
    sites

chrom_column: Chrom
start_column: Start
end_column: End
strand_column: NA
chroms: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY

norm_window_values: -5000 5000
targeted_panel: False #if targeted panel, drop sites that don't span the full normalization window
targeted_window_columns: NA NA #if targeted panel, specify column names for columns containing the start and end of the targeted range

threshold: 0.95
