#get_GC_and_mappability_content.snakefile
#Anna-Lisa Doebley
#Template made 2022-04-04
#Ha Lab
#Fred Hutchinson Cancer Research Center


###############
#config files##
###############
GC_and_map_script: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/GC_and_mappability_content/scripts/get_GC_and_map.py

tmp_dir: tmp #where your temporary outputs will go (may be large)
results_dir: results

reference_genome: /fh/fast/ha_g/grp/reference/GRCh38/GRCh38.fa #use hg38
mappability_bw: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/k100.Umap.MultiTrackMappability.hg38.bw
chrom_sizes_path: /fh/fast/ha_g/grp/reference/GRCh38/hg38.standard.chrom.sizes

chrom_column: Chrom #column containing the chromosome in your sites file
position_column: position #column containing the site position
chroms: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22

save_window: -1000 1000 #window around each site to save to outputs

#bed files containing regions to exclude
encode_exclude: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/encode_unified_GRCh38_exclusion_list.bed
centromeres: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/hg38_centromeres.bed
gaps: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/hg38_gaps.bed
patches: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/hg38_fix_patches.bed
alternative_haplotypes: /fh/fast/ha_g/user/adoebley/projects/griffin_revisions_1/genome/hg38_alternative_haplotypes.bed
