samples:
  sample_name_1:
    bam: /path/to/sample1.bam
    GC_bias: /path/to/sample1.GC_bias.txt
    mappability_bias: /path/to/sample1.mappability_bias.txt
  sample_name_2:
    bam: /path/to/sample2.bam
    GC_bias: /path/to/sample2.GC_bias.txt
    mappability_bias: /path/to/sample2.mappability_bias.txt
 